### ISSUE TITLE
Project fails on serve

### ISSUE THREAD

**Issue by dineshkumarv-ict** [itopmoon/floorplan-angular#14]
On running this application few files were missing like furnishing and helpers, please push those files into github.

**Comment by JorgeFigueroa** [comment]
jorges-MBP:floorplan-angular-master jorge$ ng serve
Your global Angular CLI version (13.0.2) is greater than your local version (8.3.29). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
10% building 3/3 modules 0 active(node:88465) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
ℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.06 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 154 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 756 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 346 kB [initial] [rendered]
Date: 2021-11-14T00:10:17.831Z - Hash: f1f74a62371d89864cf2 - Time: 7315ms

ERROR in app/app.component.ts:18:29 - error TS2307: Cannot find module './models/furnishings'.

18 import { FURNISHINGS } from './models/furnishings';
                               ~~~~~~~~~~~~~~~~~~~~~~
app/app.module.ts:9:31 - error TS2307: Cannot find module './components/view/view.component'.

9 import { ViewComponent } from './components/view/view.component';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app/components/chairs-layout/chairs-layout.component.ts:6:29 - error TS2307: Cannot find module '../../models/furnishings'.

6 import { FURNISHINGS } from '../../models/furnishings';
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~
app/components/chairs-layout/chairs-layout.component.ts:7:49 - error TS2307: Cannot find module '../../helpers'.

7 import { createShape, RL_FILL, RL_STROKE } from '../../helpers';
                                                  ~~~~~~~~~~~~~~~
app/components/preview-furniture/preview-furniture.component.ts:5:70 - error TS2307: Cannot find module '../../helpers'.

5 import { RL_PREVIEW_HEIGHT, RL_PREVIEW_WIDTH, createFurniture } from '../../helpers';

**Comment by itopmoon** [comment]
Should be fine now

**Comment by Vasanthvivi** [comment]
lol full project not uploaded folk
